server:
  port: 9200
  servlet:
    context-path: /security


spring:
  application:
    name: security-manager
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://192.168.118.50:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver


mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:/mapper/*.xml
